FROM pytorch/pytorch:2.0.0-cuda11.7-cudnn8-devel

RUN apt-get update && apt-get install -y build-essential git gcc g++

RUN git clone https://github.com/facebookresearch/dinov2.git

COPY . /app

WORKDIR /app

RUN pip install -r /app/requirements.txt -r /app/requirements-extras.txt

ENTRYPOINT [ "/entrypoint.sh" ]