FROM pytorch/pytorch:2.0.0-cuda11.7-cudnn8-devel

RUN apt-get update && apt-get install -y build-essential git gcc g++

RUN git clone https://github.com/facebookresearch/dinov2.git

RUN pip install -r ./dinov2/requirements.txt

WORKDIR /app